name: Build
on: [ push, pull_request ]

jobs:
  build-java-5-6-7:
    strategy:
      matrix:
        java-version: [ 6, 7 ]
        os: [ubuntu-latest, windows-latest]

    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Configure Java 8
        uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: 8
          cache: gradle

      - name: Build with Java 8 once to download dependencies; HTTPS does not work with older Java versions
        continue-on-error: true
        uses: gradle/gradle-build-action@v2
        with:
          gradle-version: 1.12
          arguments: assemble --no-daemon

      - name: Configure JDK ${{ matrix.java-version }}
        uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: ${{ matrix.java-version }}
          cache: gradle

      - name: Build
        continue-on-error: true
        uses: gradle/gradle-build-action@v2
        with:
          gradle-version: 1.12
          build-root-directory: picocli-legacy-tests/
          arguments: clean build --no-daemon
